### ISSUE TITLE
小提议

### ISSUE THREAD

**Issue by sonderlau** [MEP218713/MathematicalModeling-Summary#1]
这么多比赛 可否把对应比赛是否拿到奖项/具体名次列出来 方便做参考

**Comment by MEP218713** [comment]
感谢提议~我会尽快在明后两天补充上去！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月26日(周一) 晚上10:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [MEP218713/MathematicalModeling-Summary] 小提议 (#1)




 
这么多比赛 可否把对应比赛是否拿到奖项/具体名次列出来 方便做参考

**Comment by sonderlau** [comment]
Thanks.
